export interface Theme {
  id: string;
  name: string;
  nameAr: string;
  category: 'light' | 'dark' | 'professional' | 'modern' | 'elegant';
  colors: {
    background: string;
    surface: string;
    surfaceHover: string;
    border: string;
    borderMuted: string;
    text: string;
    textSecondary: string;
    textMuted: string;
    primary: string;
    primaryHover: string;
    primaryLight: string;
    accent: string;
    accentHover: string;
    success: string;
    successLight: string;
    warning: string;
    warningLight: string;
    error: string;
    errorLight: string;
    scrollbarTrack: string;
    scrollbarThumb: string;
    scrollbarThumbHover: string;
  };
}

export const themes: Theme[] = [
  {
    id: 'light-default',
    name: 'Light Default',
    nameAr: 'الافتراضي الفاتح',
    category: 'light',
    colors: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceHover: '#F1F5F9',
      border: '#E2E8F0',
      borderMuted: '#CBD5E1',
      text: '#1E293B',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      primary: '#0EA5E9',
      primaryHover: '#0284C7',
      primaryLight: '#E0F2FE',
      accent: '#0EA5E9',
      accentHover: '#0284C7',
      success: '#10B981',
      successLight: '#D1FAE5',
      warning: '#F59E0B',
      warningLight: '#FEF3C7',
      error: '#EF4444',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#F1F5F9',
      scrollbarThumb: '#CBD5E1',
      scrollbarThumbHover: '#94A3B8',
    },
  },
  {
    id: 'soft-white',
    name: 'Soft White',
    nameAr: 'ابيض ناعم',
    category: 'light',
    colors: {
      background: '#FAFAFA',
      surface: '#FFFFFF',
      surfaceHover: '#F5F5F5',
      border: '#E5E5E5',
      borderMuted: '#D4D4D4',
      text: '#262626',
      textSecondary: '#525252',
      textMuted: '#A3A3A3',
      primary: '#3B82F6',
      primaryHover: '#2563EB',
      primaryLight: '#DBEAFE',
      accent: '#3B82F6',
      accentHover: '#2563EB',
      success: '#22C55E',
      successLight: '#DCFCE7',
      warning: '#EAB308',
      warningLight: '#FEF9C3',
      error: '#EF4444',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#F5F5F5',
      scrollbarThumb: '#D4D4D4',
      scrollbarThumbHover: '#A3A3A3',
    },
  },
  {
    id: 'warm-cream',
    name: 'Warm Cream',
    nameAr: 'كريمي دافئ',
    category: 'light',
    colors: {
      background: '#FFFBF5',
      surface: '#FFFFFF',
      surfaceHover: '#FEF7ED',
      border: '#FED7AA',
      borderMuted: '#FDBA74',
      text: '#431407',
      textSecondary: '#78350F',
      textMuted: '#A16207',
      primary: '#EA580C',
      primaryHover: '#C2410C',
      primaryLight: '#FFEDD5',
      accent: '#EA580C',
      accentHover: '#C2410C',
      success: '#16A34A',
      successLight: '#DCFCE7',
      warning: '#CA8A04',
      warningLight: '#FEF9C3',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#FEF7ED',
      scrollbarThumb: '#FED7AA',
      scrollbarThumbHover: '#FDBA74',
    },
  },
  {
    id: 'cool-gray',
    name: 'Cool Gray',
    nameAr: 'رمادي بارد',
    category: 'light',
    colors: {
      background: '#F3F4F6',
      surface: '#FFFFFF',
      surfaceHover: '#E5E7EB',
      border: '#D1D5DB',
      borderMuted: '#9CA3AF',
      text: '#111827',
      textSecondary: '#374151',
      textMuted: '#6B7280',
      primary: '#4B5563',
      primaryHover: '#374151',
      primaryLight: '#F3F4F6',
      accent: '#6366F1',
      accentHover: '#4F46E5',
      success: '#10B981',
      successLight: '#D1FAE5',
      warning: '#F59E0B',
      warningLight: '#FEF3C7',
      error: '#EF4444',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#E5E7EB',
      scrollbarThumb: '#9CA3AF',
      scrollbarThumbHover: '#6B7280',
    },
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    nameAr: 'نسيم المحيط',
    category: 'light',
    colors: {
      background: '#F0FDFA',
      surface: '#FFFFFF',
      surfaceHover: '#CCFBF1',
      border: '#99F6E4',
      borderMuted: '#5EEAD4',
      text: '#134E4A',
      textSecondary: '#115E59',
      textMuted: '#0F766E',
      primary: '#14B8A6',
      primaryHover: '#0D9488',
      primaryLight: '#CCFBF1',
      accent: '#14B8A6',
      accentHover: '#0D9488',
      success: '#22C55E',
      successLight: '#DCFCE7',
      warning: '#EAB308',
      warningLight: '#FEF9C3',
      error: '#EF4444',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#CCFBF1',
      scrollbarThumb: '#5EEAD4',
      scrollbarThumbHover: '#2DD4BF',
    },
  },
  {
    id: 'dark-default',
    name: 'Dark Default',
    nameAr: 'الافتراضي الداكن',
    category: 'dark',
    colors: {
      background: '#0F172A',
      surface: '#1E293B',
      surfaceHover: '#334155',
      border: '#334155',
      borderMuted: '#475569',
      text: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#64748B',
      primary: '#38BDF8',
      primaryHover: '#0EA5E9',
      primaryLight: '#0C4A6E',
      accent: '#38BDF8',
      accentHover: '#0EA5E9',
      success: '#34D399',
      successLight: '#064E3B',
      warning: '#FBBF24',
      warningLight: '#713F12',
      error: '#F87171',
      errorLight: '#7F1D1D',
      scrollbarTrack: '#1E293B',
      scrollbarThumb: '#475569',
      scrollbarThumbHover: '#64748B',
    },
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    nameAr: 'ازرق منتصف الليل',
    category: 'dark',
    colors: {
      background: '#0A1628',
      surface: '#152238',
      surfaceHover: '#1E3A5F',
      border: '#1E3A5F',
      borderMuted: '#2563EB',
      text: '#F0F9FF',
      textSecondary: '#BAE6FD',
      textMuted: '#7DD3FC',
      primary: '#3B82F6',
      primaryHover: '#60A5FA',
      primaryLight: '#1E3A8A',
      accent: '#3B82F6',
      accentHover: '#60A5FA',
      success: '#4ADE80',
      successLight: '#14532D',
      warning: '#FCD34D',
      warningLight: '#713F12',
      error: '#FB7185',
      errorLight: '#881337',
      scrollbarTrack: '#152238',
      scrollbarThumb: '#1E3A5F',
      scrollbarThumbHover: '#2563EB',
    },
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    nameAr: 'فحمي',
    category: 'dark',
    colors: {
      background: '#171717',
      surface: '#262626',
      surfaceHover: '#404040',
      border: '#404040',
      borderMuted: '#525252',
      text: '#FAFAFA',
      textSecondary: '#D4D4D4',
      textMuted: '#A3A3A3',
      primary: '#22D3EE',
      primaryHover: '#06B6D4',
      primaryLight: '#164E63',
      accent: '#22D3EE',
      accentHover: '#06B6D4',
      success: '#4ADE80',
      successLight: '#14532D',
      warning: '#FACC15',
      warningLight: '#713F12',
      error: '#F87171',
      errorLight: '#7F1D1D',
      scrollbarTrack: '#262626',
      scrollbarThumb: '#525252',
      scrollbarThumbHover: '#737373',
    },
  },
  {
    id: 'deep-space',
    name: 'Deep Space',
    nameAr: 'الفضاء العميق',
    category: 'dark',
    colors: {
      background: '#030712',
      surface: '#111827',
      surfaceHover: '#1F2937',
      border: '#1F2937',
      borderMuted: '#374151',
      text: '#F9FAFB',
      textSecondary: '#E5E7EB',
      textMuted: '#9CA3AF',
      primary: '#818CF8',
      primaryHover: '#6366F1',
      primaryLight: '#312E81',
      accent: '#818CF8',
      accentHover: '#6366F1',
      success: '#34D399',
      successLight: '#064E3B',
      warning: '#FBBF24',
      warningLight: '#78350F',
      error: '#F87171',
      errorLight: '#7F1D1D',
      scrollbarTrack: '#111827',
      scrollbarThumb: '#374151',
      scrollbarThumbHover: '#4B5563',
    },
  },
  {
    id: 'forest-night',
    name: 'Forest Night',
    nameAr: 'ليل الغابة',
    category: 'dark',
    colors: {
      background: '#052E16',
      surface: '#14532D',
      surfaceHover: '#166534',
      border: '#166534',
      borderMuted: '#22C55E',
      text: '#F0FDF4',
      textSecondary: '#BBF7D0',
      textMuted: '#86EFAC',
      primary: '#4ADE80',
      primaryHover: '#22C55E',
      primaryLight: '#14532D',
      accent: '#4ADE80',
      accentHover: '#22C55E',
      success: '#34D399',
      successLight: '#064E3B',
      warning: '#FCD34D',
      warningLight: '#713F12',
      error: '#FCA5A5',
      errorLight: '#7F1D1D',
      scrollbarTrack: '#14532D',
      scrollbarThumb: '#22C55E',
      scrollbarThumbHover: '#4ADE80',
    },
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    nameAr: 'ازرق مؤسسي',
    category: 'professional',
    colors: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceHover: '#EFF6FF',
      border: '#BFDBFE',
      borderMuted: '#93C5FD',
      text: '#1E3A5F',
      textSecondary: '#1E40AF',
      textMuted: '#3B82F6',
      primary: '#2563EB',
      primaryHover: '#1D4ED8',
      primaryLight: '#DBEAFE',
      accent: '#2563EB',
      accentHover: '#1D4ED8',
      success: '#059669',
      successLight: '#D1FAE5',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#EFF6FF',
      scrollbarThumb: '#93C5FD',
      scrollbarThumbHover: '#3B82F6',
    },
  },
  {
    id: 'executive-gray',
    name: 'Executive Gray',
    nameAr: 'رمادي تنفيذي',
    category: 'professional',
    colors: {
      background: '#F9FAFB',
      surface: '#FFFFFF',
      surfaceHover: '#F3F4F6',
      border: '#D1D5DB',
      borderMuted: '#9CA3AF',
      text: '#111827',
      textSecondary: '#374151',
      textMuted: '#6B7280',
      primary: '#374151',
      primaryHover: '#1F2937',
      primaryLight: '#F3F4F6',
      accent: '#4F46E5',
      accentHover: '#4338CA',
      success: '#059669',
      successLight: '#D1FAE5',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#F3F4F6',
      scrollbarThumb: '#9CA3AF',
      scrollbarThumbHover: '#6B7280',
    },
  },
  {
    id: 'banking-green',
    name: 'Banking Green',
    nameAr: 'اخضر مصرفي',
    category: 'professional',
    colors: {
      background: '#F0FDF4',
      surface: '#FFFFFF',
      surfaceHover: '#DCFCE7',
      border: '#BBF7D0',
      borderMuted: '#86EFAC',
      text: '#14532D',
      textSecondary: '#166534',
      textMuted: '#22C55E',
      primary: '#16A34A',
      primaryHover: '#15803D',
      primaryLight: '#DCFCE7',
      accent: '#16A34A',
      accentHover: '#15803D',
      success: '#059669',
      successLight: '#D1FAE5',
      warning: '#CA8A04',
      warningLight: '#FEF9C3',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#DCFCE7',
      scrollbarThumb: '#86EFAC',
      scrollbarThumbHover: '#4ADE80',
    },
  },
  {
    id: 'legal-navy',
    name: 'Legal Navy',
    nameAr: 'كحلي قانوني',
    category: 'professional',
    colors: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceHover: '#F1F5F9',
      border: '#CBD5E1',
      borderMuted: '#94A3B8',
      text: '#0F172A',
      textSecondary: '#1E293B',
      textMuted: '#475569',
      primary: '#1E3A8A',
      primaryHover: '#1E40AF',
      primaryLight: '#DBEAFE',
      accent: '#1E3A8A',
      accentHover: '#1E40AF',
      success: '#047857',
      successLight: '#D1FAE5',
      warning: '#B45309',
      warningLight: '#FEF3C7',
      error: '#B91C1C',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#F1F5F9',
      scrollbarThumb: '#94A3B8',
      scrollbarThumbHover: '#64748B',
    },
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    nameAr: 'بسيط ونظيف',
    category: 'modern',
    colors: {
      background: '#FFFFFF',
      surface: '#FAFAFA',
      surfaceHover: '#F5F5F5',
      border: '#E5E5E5',
      borderMuted: '#D4D4D4',
      text: '#171717',
      textSecondary: '#404040',
      textMuted: '#737373',
      primary: '#171717',
      primaryHover: '#262626',
      primaryLight: '#F5F5F5',
      accent: '#0EA5E9',
      accentHover: '#0284C7',
      success: '#22C55E',
      successLight: '#F0FDF4',
      warning: '#F59E0B',
      warningLight: '#FFFBEB',
      error: '#EF4444',
      errorLight: '#FEF2F2',
      scrollbarTrack: '#FAFAFA',
      scrollbarThumb: '#D4D4D4',
      scrollbarThumbHover: '#A3A3A3',
    },
  },
  {
    id: 'tech-slate',
    name: 'Tech Slate',
    nameAr: 'رمادي تقني',
    category: 'modern',
    colors: {
      background: '#F1F5F9',
      surface: '#FFFFFF',
      surfaceHover: '#E2E8F0',
      border: '#CBD5E1',
      borderMuted: '#94A3B8',
      text: '#0F172A',
      textSecondary: '#334155',
      textMuted: '#64748B',
      primary: '#0F172A',
      primaryHover: '#1E293B',
      primaryLight: '#E2E8F0',
      accent: '#06B6D4',
      accentHover: '#0891B2',
      success: '#10B981',
      successLight: '#ECFDF5',
      warning: '#F59E0B',
      warningLight: '#FFFBEB',
      error: '#EF4444',
      errorLight: '#FEF2F2',
      scrollbarTrack: '#E2E8F0',
      scrollbarThumb: '#94A3B8',
      scrollbarThumbHover: '#64748B',
    },
  },
  {
    id: 'startup-fresh',
    name: 'Startup Fresh',
    nameAr: 'منعش للشركات الناشئة',
    category: 'modern',
    colors: {
      background: '#FAFAFA',
      surface: '#FFFFFF',
      surfaceHover: '#F5F5F5',
      border: '#E5E5E5',
      borderMuted: '#D4D4D4',
      text: '#18181B',
      textSecondary: '#3F3F46',
      textMuted: '#71717A',
      primary: '#2563EB',
      primaryHover: '#1D4ED8',
      primaryLight: '#EFF6FF',
      accent: '#2563EB',
      accentHover: '#1D4ED8',
      success: '#22C55E',
      successLight: '#F0FDF4',
      warning: '#EAB308',
      warningLight: '#FEFCE8',
      error: '#EF4444',
      errorLight: '#FEF2F2',
      scrollbarTrack: '#F5F5F5',
      scrollbarThumb: '#D4D4D4',
      scrollbarThumbHover: '#A3A3A3',
    },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    nameAr: 'ذهبي وردي',
    category: 'elegant',
    colors: {
      background: '#FDF2F8',
      surface: '#FFFFFF',
      surfaceHover: '#FCE7F3',
      border: '#FBCFE8',
      borderMuted: '#F9A8D4',
      text: '#831843',
      textSecondary: '#9D174D',
      textMuted: '#BE185D',
      primary: '#DB2777',
      primaryHover: '#BE185D',
      primaryLight: '#FCE7F3',
      accent: '#CA8A04',
      accentHover: '#A16207',
      success: '#059669',
      successLight: '#D1FAE5',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#FCE7F3',
      scrollbarThumb: '#F9A8D4',
      scrollbarThumbHover: '#F472B6',
    },
  },
  {
    id: 'emerald-luxury',
    name: 'Emerald Luxury',
    nameAr: 'زمردي فاخر',
    category: 'elegant',
    colors: {
      background: '#ECFDF5',
      surface: '#FFFFFF',
      surfaceHover: '#D1FAE5',
      border: '#A7F3D0',
      borderMuted: '#6EE7B7',
      text: '#064E3B',
      textSecondary: '#047857',
      textMuted: '#059669',
      primary: '#059669',
      primaryHover: '#047857',
      primaryLight: '#D1FAE5',
      accent: '#B45309',
      accentHover: '#92400E',
      success: '#16A34A',
      successLight: '#DCFCE7',
      warning: '#CA8A04',
      warningLight: '#FEF9C3',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#D1FAE5',
      scrollbarThumb: '#6EE7B7',
      scrollbarThumbHover: '#34D399',
    },
  },
  {
    id: 'royal-bronze',
    name: 'Royal Bronze',
    nameAr: 'برونزي ملكي',
    category: 'elegant',
    colors: {
      background: '#FFFBEB',
      surface: '#FFFFFF',
      surfaceHover: '#FEF3C7',
      border: '#FDE68A',
      borderMuted: '#FCD34D',
      text: '#78350F',
      textSecondary: '#92400E',
      textMuted: '#B45309',
      primary: '#B45309',
      primaryHover: '#92400E',
      primaryLight: '#FEF3C7',
      accent: '#0D9488',
      accentHover: '#0F766E',
      success: '#059669',
      successLight: '#D1FAE5',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      scrollbarTrack: '#FEF3C7',
      scrollbarThumb: '#FCD34D',
      scrollbarThumbHover: '#FBBF24',
    },
  },
];

export const getThemeById = (id: string): Theme | undefined => {
  return themes.find(t => t.id === id);
};

export const getThemesByCategory = (category: Theme['category']): Theme[] => {
  return themes.filter(t => t.category === category);
};

export const defaultThemeId = 'light-default';
