/*
  # Security Fix: Revoke PUBLIC EXECUTE on all SECURITY DEFINER functions

  Previous migration revoked from anon/authenticated roles specifically, but since
  PostgreSQL grants EXECUTE to PUBLIC by default, and anon/authenticated inherit from
  PUBLIC, those revocations were ineffective. This migration revokes from PUBLIC
  (which covers all roles including anon and authenticated), then selectively
  re-grants to authenticated only for legitimate RPC endpoints.
*/

-- ============================================================
-- STEP 1: REVOKE from PUBLIC for ALL internal/trigger functions
-- ============================================================

REVOKE EXECUTE ON FUNCTION public._get_je_net_amount(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public._refresh_invoice_payment_status(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public._refresh_purchase_payment_status(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public._vat_derive_rate(public.vat_category_enum) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.apply_leave_approval() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_create_purchase_receipt_journal() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_post_expense_entry() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_base_currency_amounts() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_commission_on_sale() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_sale_commission() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_period_lock() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.compute_operating_expense_vat() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.compute_partner_contribution_vat() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.compute_purchase_item_vat() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.compute_setup_expense_vat() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_expense_from_partner_contribution() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_expense_on_payroll_posted() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_journal_entry_on_payroll_paid() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_product_costing_on_insert() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.deduct_wastage_from_inventory() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.enforce_optimistic_lock() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.enforce_strict_balance() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ensure_optimistic_lock() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_audit_trigger() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_auto_audit_log() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_auto_create_employee_for_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_guard_sale_immutability() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_period_lock_journal_lines() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_period_lock_purchases() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_period_lock_sales() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_refresh_gl_monthly_balances() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_sync_user_changes_to_employee() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_zatca_stamp_invoice() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_cash_transactions_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_expenses_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_inventory_movements_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_operating_expenses_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_partner_contributions_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_partner_settlements_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_purchase_items_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_purchases_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_sale_items_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_sales_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.freeze_setup_expenses_financials() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_custody_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_entry_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_expense_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_journal_entry_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_shift_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_wastage_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.guard_finalize_reconciliation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.guard_finalized_reconciliation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.guard_invoice_payment_allocation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.guard_purchase_payment_allocation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.guard_reconciliation_match() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_sale_status_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.increment_version() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.initialize_new_branch_stock() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_audit_trail() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.post_operating_expense_gl() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_closed_period_modifications() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_commission_delete() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_financial_delete() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_hard_delete_allocation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_hard_delete_recon() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_self_branch_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_terminated_employee_salary() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.process_sale_inventory_out() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_audit_logs() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_cash_transactions_closed_periods() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_closed_periods() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_expenses_closed_periods() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_journal_entries_closed_periods() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_posted_entries() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_posted_entry_lines() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_purchases_closed_periods() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_sales_closed_periods() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_loyalty_on_sale_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_payroll_totals() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_expense_cash_movement() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_sale_cash_movement() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_vat_tx_from_operating_expense() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_vat_tx_from_partner_contribution() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_vat_tx_from_purchase() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_vat_tx_from_sale() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_vat_tx_from_setup_expense() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.restore_wastage_to_inventory() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_commission_branch_id() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_purchase_item_branch_id() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_sale_item_branch_id() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_bsl_is_matched() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_costing_from_inventory() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_inventory_from_costing() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_salla_order_to_inventory() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.touch_cfm_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.touch_updated_at_bank_recon() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trg_partner_settlement_post_gl() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trg_setup_expense_post_gl() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_branch_settings_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_cash_shifts_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_companies_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_custody_totals() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_customer_classification_tags() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_customer_metrics_on_sale() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_customer_metrics_on_sale_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_customer_stats_after_sale() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_employees_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_hr_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_moving_average_on_purchase() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_sale_profit_trigger() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_salla_orders_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_settings_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_updated_at_column() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_users_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_partner_ownership_total() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_commission_on_sale_cancel() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_sale_commission() FROM PUBLIC;

-- ============================================================
-- STEP 2: REVOKE from PUBLIC for all RPC functions (re-grant to authenticated below)
-- ============================================================

REVOKE EXECUTE ON FUNCTION public.add_custody_settlement_atomic(uuid, text, numeric, text, text, text, date, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.add_loyalty_points_transaction(uuid, uuid, integer, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.allocate_customer_payment(uuid, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.allocate_supplier_payment(uuid, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.approve_payroll_run(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.assign_branch_to_user(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_match_bank_transactions(uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_post_cogs_on_sale(uuid, uuid, uuid, numeric, date, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_customer_tier(numeric, integer, timestamptz) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_customer_tier(numeric, integer, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_end_of_service(uuid, date, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_monthly_depreciation(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_sale_profit(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_salla_sales(date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_shift_expected_balance(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_valid_loyalty_points(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_wastage_cost(date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.cancel_draft_payroll_run(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_user_permission(text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_employee_custody_atomic(uuid, uuid, numeric, text, uuid, text, text, text, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_payroll_run(integer, integer, uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_purchase_receipt_journal_entry(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_sale_atomic(jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_sale_journal_entry_test(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.delete_draft_payroll_run(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.execute_sql_as_admin(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.finalize_bank_reconciliation(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fix_customer_metrics_for_existing_data() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_add_user_to_company(uuid, uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_can_bypass_period_lock() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_can_manage_company_data(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_check_period_open(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_cleanup_old_errors(integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_close_accounting_period(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_create_company(text, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_distribute_monthly_profit(integer, integer, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_enqueue_zatca_retry(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_alerts(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_audit_summary(date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_company_from_branch(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_error_stats(integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_locked_period_name(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_my_role() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_user_company_id() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_user_company_ids() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_get_user_company_role(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_is_admin_or_super() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_is_company_admin(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_is_company_manager(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_is_current_user_super_admin() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_is_period_locked(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_is_period_locked_for_user(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_is_super_admin() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_log_audit(text, text, uuid, jsonb, jsonb, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_log_closed_period_modification(text, uuid, text, jsonb, jsonb, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_log_error(text, text, text, text, text, text, text, text, jsonb, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_next_invoice_number(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_record_partner_withdrawal(uuid, numeric, text, text, text, date, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_remove_user_from_company(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_renew_iqama(uuid, integer, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_reopen_accounting_period(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_resolve_error(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_super_admin_update_setup_expense(uuid, numeric, date, text, text, text, uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_switch_primary_company(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_update_company_member_role(uuid, uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_update_zatca_hash(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_user_has_branch_access(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_user_has_company_access(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_depreciation_entries(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_payroll_run(uuid, integer, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_active_compensation_plan(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_ap_aging(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_ar_aging(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_auth_email_by_user_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_balance_sheet(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_balance_sheet_v2(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_bank_reconciliation_summary(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_branch_stock_summary(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_cash_flow_statement(uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_consolidated_sales_summary(date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_db_health_report() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_dso(uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_employee_open_custodies(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_financial_summary(date, date, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_financial_summary_secure(date, date, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_gl_monthly_balances(uuid, date, date, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_income_statement(uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_income_statement_v2(uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_my_role() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_open_cash_register() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_register_current_balance(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_total_depreciation_for_period(date, date, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_trial_balance(uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_trial_balance(date, date, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_trial_balance_v2(uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_user_branch_id() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_user_permissions(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_user_role() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_vat_summary(uuid, integer, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.import_bank_statement(uuid, date, date, numeric, numeric, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.initialize_branch_onboarding() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_super_admin() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_security_event(text, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.manual_match_bank_transaction(uuid, uuid, numeric, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pay_payroll_run(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.perform_atomic_restore(jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.post_partner_operation_atomic(jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.post_partner_settlement_atomic(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.process_purchase_receipt_atomic(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_all_customer_metrics() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_all_customer_stats() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_all_valid_loyalty_points() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.safe_delete_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.settle_vat_period(uuid, integer, integer, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.test_partner_operation_integrity(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.test_purchase_receipt_integrity(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trusted_change_purchase_status(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trusted_change_sale_status(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trusted_void_expense(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trusted_void_operating_expense(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trusted_void_purchase(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trusted_void_sale(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trusted_void_setup_expense(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.unmatch_bank_transaction(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_purchase_status(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_sale_status(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_setup_expense_amount(uuid, numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.upsert_user_permissions(uuid, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_restore_readiness() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.verify_gl_balance(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_expense(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_invoice_payment(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_journal_entry(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_operating_expense(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_partner_operation_atomic(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_partner_settlement(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_purchase(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_purchase_payment(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_sale(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_setup_expense(uuid, text) FROM PUBLIC;

-- lookup_auth_email_by_username is needed for login flow - keep anon access
REVOKE EXECUTE ON FUNCTION public.fn_log_error(text, text, text, text, text, text, text, text, jsonb, jsonb) FROM PUBLIC;

-- ============================================================
-- STEP 3: Re-grant to authenticated for all legitimate RPC endpoints
-- ============================================================

GRANT EXECUTE ON FUNCTION public.add_custody_settlement_atomic(uuid, text, numeric, text, text, text, date, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.add_loyalty_points_transaction(uuid, uuid, integer, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.allocate_customer_payment(uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.allocate_supplier_payment(uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_payroll_run(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assign_branch_to_user(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auto_match_bank_transactions(uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auto_post_cogs_on_sale(uuid, uuid, uuid, numeric, date, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_customer_tier(numeric, integer, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_customer_tier(numeric, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_end_of_service(uuid, date, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_monthly_depreciation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_sale_profit(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_salla_sales(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_shift_expected_balance(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_valid_loyalty_points(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_wastage_cost(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_draft_payroll_run(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_user_permission(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_employee_custody_atomic(uuid, uuid, numeric, text, uuid, text, text, text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_payroll_run(integer, integer, uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_purchase_receipt_journal_entry(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_sale_atomic(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_sale_journal_entry_test(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_draft_payroll_run(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.execute_sql_as_admin(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_bank_reconciliation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fix_customer_metrics_for_existing_data() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_add_user_to_company(uuid, uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_can_bypass_period_lock() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_can_manage_company_data(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_check_period_open(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_cleanup_old_errors(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_close_accounting_period(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_create_company(text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_distribute_monthly_profit(integer, integer, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_enqueue_zatca_retry(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_alerts(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_audit_summary(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_company_from_branch(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_error_stats(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_locked_period_name(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_my_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_user_company_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_user_company_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_user_company_role(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_is_admin_or_super() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_is_company_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_is_company_manager(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_is_current_user_super_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_is_period_locked(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_is_period_locked_for_user(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_is_super_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_log_audit(text, text, uuid, jsonb, jsonb, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_log_closed_period_modification(text, uuid, text, jsonb, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_log_error(text, text, text, text, text, text, text, text, jsonb, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_next_invoice_number(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_record_partner_withdrawal(uuid, numeric, text, text, text, date, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_remove_user_from_company(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_renew_iqama(uuid, integer, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_reopen_accounting_period(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_resolve_error(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_super_admin_update_setup_expense(uuid, numeric, date, text, text, text, uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_switch_primary_company(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_update_company_member_role(uuid, uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_update_zatca_hash(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_user_has_branch_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_user_has_company_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_depreciation_entries(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_payroll_run(uuid, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_active_compensation_plan(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_ap_aging(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_ar_aging(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_auth_email_by_user_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_balance_sheet(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_balance_sheet_v2(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_bank_reconciliation_summary(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_branch_stock_summary(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_cash_flow_statement(uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_consolidated_sales_summary(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_db_health_report() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_dso(uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_employee_open_custodies(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_financial_summary(date, date, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_financial_summary_secure(date, date, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_gl_monthly_balances(uuid, date, date, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_income_statement(uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_income_statement_v2(uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_open_cash_register() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_register_current_balance(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_total_depreciation_for_period(date, date, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_trial_balance(uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_trial_balance(date, date, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_trial_balance_v2(uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_branch_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_permissions(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_vat_summary(uuid, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.import_bank_statement(uuid, date, date, numeric, numeric, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.initialize_branch_onboarding() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_super_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_security_event(text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.manual_match_bank_transaction(uuid, uuid, numeric, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pay_payroll_run(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.perform_atomic_restore(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.post_partner_operation_atomic(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.post_partner_settlement_atomic(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_purchase_receipt_atomic(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recalculate_all_customer_metrics() TO authenticated;
GRANT EXECUTE ON FUNCTION public.recalculate_all_customer_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.recalculate_all_valid_loyalty_points() TO authenticated;
GRANT EXECUTE ON FUNCTION public.safe_delete_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.settle_vat_period(uuid, integer, integer, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.test_partner_operation_integrity(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.test_purchase_receipt_integrity(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trusted_change_purchase_status(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trusted_change_sale_status(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trusted_void_expense(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trusted_void_operating_expense(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trusted_void_purchase(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trusted_void_sale(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trusted_void_setup_expense(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unmatch_bank_transaction(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_purchase_status(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_sale_status(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_setup_expense_amount(uuid, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_user_permissions(uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_restore_readiness() TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_gl_balance(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_expense(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_invoice_payment(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_journal_entry(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_operating_expense(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_partner_operation_atomic(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_partner_settlement(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_purchase(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_purchase_payment(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_sale(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_setup_expense(uuid, text) TO authenticated;

-- Keep lookup_auth_email_by_username accessible to anon (needed for login flow)
-- It was already handled in the previous migration
