/*
  # Security Hardening: search_path Pinning and RLS Tightening

  Critical security fixes:
  1. Pin search_path in 29 SECURITY DEFINER functions
  2. Fix sales_profit_summary VIEW to SECURITY INVOKER
  3. Close unrestricted RLS policy on customers
*/

CREATE OR REPLACE FUNCTION calculate_sale_profit(sale_id_param uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_total_cost numeric; v_total_revenue numeric; v_gross_profit numeric; v_profit_margin numeric; BEGIN SELECT COALESCE(SUM(purchase_price * quantity), 0) INTO v_total_cost FROM sale_items WHERE sale_id = sale_id_param; SELECT total INTO v_total_revenue FROM sales WHERE id = sale_id_param; v_gross_profit := v_total_revenue - v_total_cost; IF v_total_revenue > 0 THEN v_profit_margin := (v_gross_profit / v_total_revenue) * 100; ELSE v_profit_margin := 0; END IF; UPDATE sales SET total_cost = v_total_cost, gross_profit = v_gross_profit, profit_margin = v_profit_margin, updated_at = now() WHERE id = sale_id_param; END; $$;

CREATE OR REPLACE FUNCTION update_sale_profit_trigger() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF TG_OP = 'DELETE' THEN PERFORM calculate_sale_profit(OLD.sale_id); ELSE PERFORM calculate_sale_profit(NEW.sale_id); END IF; RETURN NULL; END; $$;

CREATE OR REPLACE FUNCTION freeze_sales_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on sales. Record ID: %', OLD.id; END IF; IF NEW.subtotal IS DISTINCT FROM OLD.subtotal OR NEW.tax IS DISTINCT FROM OLD.tax OR NEW.discount IS DISTINCT FROM OLD.discount OR NEW.total IS DISTINCT FROM OLD.total OR NEW.delivery_charge IS DISTINCT FROM OLD.delivery_charge THEN RAISE EXCEPTION 'Financial values (subtotal, tax, discount, total, delivery_charge) on sales are frozen after creation. Use void/reversal. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_sale_items_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on sale_items. Record ID: %', OLD.id; END IF; IF NEW.quantity IS DISTINCT FROM OLD.quantity OR NEW.unit_price IS DISTINCT FROM OLD.unit_price OR NEW.discount IS DISTINCT FROM OLD.discount OR NEW.total IS DISTINCT FROM OLD.total OR NEW.purchase_price IS DISTINCT FROM OLD.purchase_price THEN RAISE EXCEPTION 'Financial values on sale_items are frozen after creation. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_purchases_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on purchases. Record ID: %', OLD.id; END IF; IF NEW.subtotal IS DISTINCT FROM OLD.subtotal OR NEW.tax IS DISTINCT FROM OLD.tax OR NEW.discount IS DISTINCT FROM OLD.discount OR NEW.total IS DISTINCT FROM OLD.total THEN RAISE EXCEPTION 'Financial values on purchases are frozen after creation. Use void/reversal. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_purchase_items_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on purchase_items. Record ID: %', OLD.id; END IF; IF NEW.quantity IS DISTINCT FROM OLD.quantity OR NEW.unit_price IS DISTINCT FROM OLD.unit_price OR NEW.discount IS DISTINCT FROM OLD.discount OR NEW.total IS DISTINCT FROM OLD.total THEN RAISE EXCEPTION 'Financial values on purchase_items are frozen after creation. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_expenses_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on expenses. Record ID: %', OLD.id; END IF; IF NEW.amount IS DISTINCT FROM OLD.amount THEN RAISE EXCEPTION 'Financial value (amount) on expenses is frozen after creation. Use void/reversal. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_operating_expenses_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on operating_expenses. Record ID: %', OLD.id; END IF; IF NEW.amount IS DISTINCT FROM OLD.amount THEN RAISE EXCEPTION 'Financial value (amount) on operating_expenses is frozen after creation. Use void/reversal. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_cash_transactions_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on cash_transactions. Record ID: %', OLD.id; END IF; IF NEW.amount IS DISTINCT FROM OLD.amount THEN RAISE EXCEPTION 'Financial value (amount) on cash_transactions is frozen after creation. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_partner_contributions_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on partner_contributions. Record ID: %', OLD.id; END IF; IF NEW.amount IS DISTINCT FROM OLD.amount THEN RAISE EXCEPTION 'Financial value (amount) on partner_contributions is frozen after creation. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_partner_settlements_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on partner_settlements. Record ID: %', OLD.id; END IF; IF NEW.amount IS DISTINCT FROM OLD.amount THEN RAISE EXCEPTION 'Financial value (amount) on partner_settlements is frozen after creation. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_setup_expenses_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on setup_expenses. Record ID: %', OLD.id; END IF; IF NEW.amount IS DISTINCT FROM OLD.amount THEN RAISE EXCEPTION 'Financial value (amount) on setup_expenses is frozen after creation. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION freeze_inventory_movements_financials() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN NEW; END IF; IF OLD.is_deleted = true THEN RAISE EXCEPTION 'Cannot update a deleted record on inventory_movements. Record ID: %', OLD.id; END IF; IF NEW.quantity IS DISTINCT FROM OLD.quantity THEN RAISE EXCEPTION 'Financial value (quantity) on inventory_movements is frozen after creation. Record ID: %', OLD.id; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION prevent_financial_delete() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN RETURN OLD; END IF; RAISE EXCEPTION 'DELETE operation is not permitted on financial table "%" - use void/reversal functions instead. Record ID: %', TG_TABLE_NAME, OLD.id; RETURN NULL; END; $$;

CREATE OR REPLACE FUNCTION generate_shift_number() RETURNS TEXT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_date TEXT; v_count INT; BEGIN v_date := TO_CHAR(NOW(), 'YYYYMMDD'); SELECT COUNT(*) + 1 INTO v_count FROM cash_shifts WHERE shift_number LIKE 'CS-' || v_date || '-%'; RETURN 'CS-' || v_date || '-' || LPAD(v_count::TEXT, 4, '0'); END; $$;

CREATE OR REPLACE FUNCTION calculate_shift_expected_balance(shift_id_param UUID) RETURNS NUMERIC LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_opening_balance NUMERIC; v_total_in NUMERIC; v_total_out NUMERIC; BEGIN SELECT opening_balance INTO v_opening_balance FROM cash_shifts WHERE id = shift_id_param; SELECT COALESCE(SUM(amount), 0) INTO v_total_in FROM cash_transactions WHERE shift_id = shift_id_param AND transaction_type = 'in'; SELECT COALESCE(SUM(amount), 0) INTO v_total_out FROM cash_transactions WHERE shift_id = shift_id_param AND transaction_type = 'out'; RETURN v_opening_balance + v_total_in - v_total_out; END; $$;

CREATE OR REPLACE FUNCTION generate_wastage_number() RETURNS TEXT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_date TEXT; v_count INT; BEGIN v_date := TO_CHAR(NOW(), 'YYYYMMDD'); SELECT COUNT(*) + 1 INTO v_count FROM inventory_movements WHERE movement_number LIKE 'WST-' || v_date || '-%' AND movement_type = 'wastage'; RETURN 'WST-' || v_date || '-' || LPAD(v_count::TEXT, 4, '0'); END; $$;

CREATE OR REPLACE FUNCTION calculate_wastage_cost(start_date DATE, end_date DATE) RETURNS TABLE (product_id UUID, product_name TEXT, total_quantity NUMERIC, unit_cost NUMERIC, total_cost NUMERIC) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN RETURN QUERY SELECT im.product_id, p.name as product_name, SUM(im.quantity) as total_quantity, p.purchase_price as unit_cost, SUM(im.quantity * p.purchase_price) as total_cost FROM inventory_movements im JOIN products p ON im.product_id = p.id WHERE im.movement_type = 'wastage' AND im.movement_date BETWEEN start_date AND end_date GROUP BY im.product_id, p.name, p.purchase_price ORDER BY total_cost DESC; END; $$;

CREATE OR REPLACE FUNCTION calculate_salla_sales(start_date DATE, end_date DATE) RETURNS TABLE (total_orders BIGINT, total_revenue NUMERIC, total_commission NUMERIC, net_revenue NUMERIC) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN RETURN QUERY SELECT COUNT(*)::BIGINT as total_orders, COALESCE(SUM(s.total), 0) as total_revenue, COALESCE(SUM(s.salla_commission), 0) as total_commission, COALESCE(SUM(s.total - COALESCE(s.salla_commission, 0)), 0) as net_revenue FROM sales s WHERE s.sales_source = 'salla' AND s.sale_date BETWEEN start_date AND end_date AND s.status != 'cancelled'; END; $$;

CREATE OR REPLACE FUNCTION calculate_customer_tier(p_total_spent numeric, p_total_purchases int, p_points_balance int) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF p_total_spent >= 50000 OR p_total_purchases >= 100 OR p_points_balance >= 5000 THEN RETURN 'platinum'; ELSIF p_total_spent >= 20000 OR p_total_purchases >= 50 OR p_points_balance >= 2000 THEN RETURN 'gold'; ELSIF p_total_spent >= 5000 OR p_total_purchases >= 20 OR p_points_balance >= 500 THEN RETURN 'silver'; ELSE RETURN 'bronze'; END IF; END; $$;

CREATE OR REPLACE FUNCTION calculate_valid_loyalty_points(p_customer_id uuid) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_total_points integer := 0; BEGIN SELECT COALESCE(SUM(CASE WHEN transaction_type = 'earned' THEN points_amount WHEN transaction_type = 'redeemed' THEN -points_amount WHEN transaction_type = 'deducted' THEN -points_amount WHEN transaction_type = 'expired' THEN -points_amount ELSE 0 END), 0) INTO v_total_points FROM loyalty_transactions WHERE customer_id = p_customer_id; RETURN GREATEST(v_total_points, 0); END; $$;

CREATE OR REPLACE FUNCTION public.recalculate_all_customer_metrics() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE customer_rec RECORD; v_total_spent numeric; v_total_purchases int; v_avg_order_value numeric; v_last_purchase_date timestamptz; v_points_balance int; v_tier text; BEGIN FOR customer_rec IN SELECT id FROM customers LOOP SELECT COALESCE(SUM(total), 0), COUNT(*), COALESCE(AVG(total), 0), MAX(sale_date) INTO v_total_spent, v_total_purchases, v_avg_order_value, v_last_purchase_date FROM sales WHERE customer_id = customer_rec.id AND status IN ('confirmed', 'draft'); v_points_balance := calculate_valid_loyalty_points(customer_rec.id); v_tier := calculate_customer_tier(v_total_spent, v_total_purchases, v_points_balance); UPDATE customers SET total_spent = v_total_spent, total_purchases = v_total_purchases, avg_order_value = v_avg_order_value, last_purchase_date = v_last_purchase_date, loyalty_points = v_points_balance, tier = v_tier, updated_at = now() WHERE id = customer_rec.id; END LOOP; END; $$;

CREATE OR REPLACE FUNCTION public.recalculate_all_valid_loyalty_points() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE customer_rec RECORD; v_valid_points integer; BEGIN FOR customer_rec IN SELECT id FROM customers LOOP v_valid_points := calculate_valid_loyalty_points(customer_rec.id); UPDATE customers SET loyalty_points = v_valid_points, updated_at = now() WHERE id = customer_rec.id; END LOOP; END; $$;

CREATE OR REPLACE FUNCTION update_customer_metrics_on_sale_change() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_customer_id uuid; v_total_spent numeric; v_total_purchases int; v_avg_order_value numeric; v_last_purchase_date timestamptz; v_points_balance int; v_tier text; BEGIN IF TG_OP = 'DELETE' THEN v_customer_id := OLD.customer_id; ELSE v_customer_id := NEW.customer_id; END IF; IF v_customer_id IS NULL THEN RETURN NEW; END IF; SELECT COALESCE(SUM(total), 0), COUNT(*), COALESCE(AVG(total), 0), MAX(sale_date) INTO v_total_spent, v_total_purchases, v_avg_order_value, v_last_purchase_date FROM sales WHERE customer_id = v_customer_id AND status IN ('confirmed', 'draft'); v_points_balance := calculate_valid_loyalty_points(v_customer_id); v_tier := calculate_customer_tier(v_total_spent, v_total_purchases, v_points_balance); UPDATE customers SET total_spent = v_total_spent, total_purchases = v_total_purchases, avg_order_value = v_avg_order_value, last_purchase_date = v_last_purchase_date, loyalty_points = v_points_balance, tier = v_tier, updated_at = now() WHERE id = v_customer_id; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION recalculate_loyalty_on_sale_change() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_customer_id uuid; v_sale_id uuid; v_status text; v_old_status text; v_points_earned int; v_transaction_exists boolean; BEGIN v_customer_id := NEW.customer_id; v_sale_id := NEW.id; v_status := NEW.status; v_old_status := OLD.status; IF v_customer_id IS NULL THEN RETURN NEW; END IF; IF v_old_status = 'confirmed' AND v_status IN ('cancelled', 'returned', 'void') THEN SELECT EXISTS(SELECT 1 FROM loyalty_transactions WHERE customer_id = v_customer_id AND sale_id = v_sale_id AND transaction_type = 'earned') INTO v_transaction_exists; IF v_transaction_exists THEN SELECT points_amount INTO v_points_earned FROM loyalty_transactions WHERE customer_id = v_customer_id AND sale_id = v_sale_id AND transaction_type = 'earned' LIMIT 1; INSERT INTO loyalty_transactions (customer_id, sale_id, transaction_type, points_amount, description, created_at) VALUES (v_customer_id, v_sale_id, 'deducted', v_points_earned, 'Points deducted due to sale ' || v_status, now()); END IF; END IF; IF v_old_status IN ('cancelled', 'returned', 'void') AND v_status = 'confirmed' THEN v_points_earned := FLOOR(NEW.total / 10); IF v_points_earned > 0 THEN INSERT INTO loyalty_transactions (customer_id, sale_id, transaction_type, points_amount, description, created_at) VALUES (v_customer_id, v_sale_id, 'earned', v_points_earned, 'Points earned from sale ' || NEW.sale_number, now()); END IF; END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION generate_expense_number() RETURNS TEXT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_date TEXT; v_count INT; BEGIN v_date := TO_CHAR(NOW(), 'YYYYMMDD'); SELECT COUNT(*) + 1 INTO v_count FROM operating_expenses WHERE expense_number LIKE 'EXP-' || v_date || '-%'; RETURN 'EXP-' || v_date || '-' || LPAD(v_count::TEXT, 4, '0'); END; $$;

CREATE OR REPLACE FUNCTION get_user_role() RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_role text; BEGIN SELECT role INTO v_role FROM users WHERE id = auth.uid(); RETURN v_role; END; $$;

CREATE OR REPLACE FUNCTION assign_branch_to_user(p_user_id uuid, p_branch_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ DECLARE v_caller_role text; BEGIN SELECT role INTO v_caller_role FROM users WHERE id = auth.uid(); IF v_caller_role NOT IN ('super_admin', 'admin') THEN RAISE EXCEPTION 'Only super_admin or admin can assign branches'; END IF; UPDATE users SET branch_id = p_branch_id WHERE id = p_user_id; END; $$;

CREATE OR REPLACE FUNCTION ensure_optimistic_lock() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN IF current_setting('app.bypass_immutable', true) = 'true' THEN NEW.version := OLD.version + 1; RETURN NEW; END IF; IF OLD.version IS DISTINCT FROM NEW.version THEN RAISE EXCEPTION 'Optimistic lock failed: record has been modified by another transaction. Table: %, ID: %', TG_TABLE_NAME, OLD.id USING HINT = 'Refresh the record and try again'; END IF; NEW.version := OLD.version + 1; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$ BEGIN NEW.updated_at := now(); RETURN NEW; END; $$;

DROP VIEW IF EXISTS sales_profit_summary;
CREATE VIEW sales_profit_summary WITH (security_invoker = true) AS SELECT s.id, s.sale_number, s.sale_date, s.customer_id, c.name as customer_name, s.subtotal, s.discount, s.tax, s.total as total_revenue, s.total_cost, s.gross_profit, s.profit_margin, s.status, s.created_at FROM sales s LEFT JOIN customers c ON s.customer_id = c.id WHERE s.status != 'cancelled' ORDER BY s.sale_date DESC;

DROP POLICY IF EXISTS "Users can update customers" ON customers;
CREATE POLICY "Authorized users can update customers" ON customers FOR UPDATE TO authenticated USING ((SELECT role FROM users WHERE id = auth.uid()) = 'super_admin' OR ((SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'accountant') AND (branch_id = (SELECT branch_id FROM users WHERE id = auth.uid()) OR branch_id IS NULL)) OR ((SELECT role FROM users WHERE id = auth.uid()) = 'cashier' AND branch_id = (SELECT branch_id FROM users WHERE id = auth.uid()))) WITH CHECK ((SELECT role FROM users WHERE id = auth.uid()) = 'super_admin' OR ((SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'accountant') AND (branch_id = (SELECT branch_id FROM users WHERE id = auth.uid()) OR branch_id IS NULL)) OR ((SELECT role FROM users WHERE id = auth.uid()) = 'cashier' AND branch_id = (SELECT branch_id FROM users WHERE id = auth.uid())));
